(function(g){var window=this;'use strict';var S3=function(a){a.oa("cardstatechange",a.Gk()&&a.Yo()?1:0)},T3=function(a,b){var c=g.Za(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Hjb=function(a){var b=g.cs(a);
a=g.fs(a);return new g.Sr(b.x,b.y,a.width,a.height)},Ijb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.EC(a,b,function(){g.FC(e);c.apply(a,arguments)},d)},W3=function(a){a=g.db(a);
delete U3[a];g.jd(U3)&&V3&&V3.stop()},Kjb=function(){V3||(V3=new g.Bu(function(){Jjb()},20));
var a=V3;a.isActive()||a.start()},Jjb=function(){var a=g.kb();
g.Wc(U3,function(b){Ljb(b,a)});
g.jd(U3)||Kjb()},X3=function(a,b,c,d){g.Vu.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Ljb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Mjb(a,a.progress);1==a.progress?(a.j=0,W3(a),a.onFinish(),a.wr()):a.isPlaying()&&a.wL()},Mjb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Njb=function(a,b){g.wb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},Y3=function(a,b,c,d,e){X3.call(this,b,c,d,e);
this.element=a},Ojb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
Y3.call(this,a,b,c,d,e)},Pjb=function(a){return Math.pow(a,3)},Qjb=function(a){return 3*a*a-2*a*a*a},Rjb=function(a){g.J.call(this);
this.B=a||window;this.j=[]},Z3=function(a){return a.baseUrl||null},$3=function(a,b){return g.Zs(g.lr(a,b),function(c){return!!c})},Sjb=function(a,b,c){function d(ua){var ma=ua.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var wa=f(ma.unsubscribedButtonText),ea=f(ma.subscribedButtonText);if(ma.subscribed){var Ba=f(ma.subscriberCountWithUnsubscribeText);var ba=f(ma.subscriberCountText)}else Ba=f(ma.subscriberCountText),ba=f(ma.subscriberCountWithSubscribeText);var Ua=null;if(ua.signinEndpoint){Ua=T3(ua,"signinEndpoint","webNavigationEndpointData","url");if(!Ua){var z,W;Ua=null==(W=g.U(null==(z=ma.signInEndpoint)?void 0:z.commandMetadata,g.J2))?void 0:
W.url}if(!Ua)return null}return wa&&(ea||Ua)?{subscribed:ma.subscribed,subscribeText:wa,subscribeCount:Ba,unsubscribeText:ea,unsubscribeCount:ba,enabled:ma.enabled,signinUrl:Ua,classic:ua.useClassicSubscribeButton}:null}
function e(ua){if(ua){var ma=[],wa=ua.videoId;wa&&ma.push("v="+wa);(wa=ua.playlistId)&&ma.push("list="+wa);(ua=ua.startTimeSeconds)&&ma.push("t="+ua);return"/watch?"+ma.join("&")}}
function f(ua){if(!ua)return null;var ma=ua.simpleText;return ma?ma:ua.runs?g.lr(ua.runs,function(wa){return wa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,x=!1,B=null,F=null,G=null,H=null,O=null,P=null;if("VIDEO"===h)g.U(l,g.pG)?m=g.U(l,g.pG).url:(P=g.U(l,g.lT),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.U(l,g.pG)?m=g.U(l,g.pG).url:(P=g.U(l,g.lT),m=e(P)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=T3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):F=f(b.subscribersText)}else"WEBSITE"===h?((G=T3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(O=f(b.additionalFeesText)),(n=T3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=T3(b,"title","accessibility","accessibilityData","label");var Y=b.endpoint?b.endpoint.clickTrackingParams:null,
la="";if(b.metadata){var na=f(b.metadata);na&&(la=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:la,callToAction:f(b.callToAction),SV:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,aE:p,playlistLength:t,channelId:u,subscribeButton:B,subscribersText:F,isSubscribe:x,targetUrl:m||null,t7:n,sessionData:Y?{itct:Y}:null,Nba:q,AC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:$3(b.impressionUrls||[],Z3),h7:$3(b.hovercardShowUrls||[],Z3),clickUrls:$3(l.loggingUrls||[],Z3),visualElement:g.vF(b.trackingParams),productPrice:H,additionalFeesText:O,watchEndpoint:P||null}},Tjb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:$3(a.impressionUrls||[],Z3),elements:$3(a.elements||[],function(d,e){return Sjb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.vF(a.trackingParams));return c},Ujb=function(a){g.wV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.cS(a)||g.eS(a);this.events=new g.IK(this);g.L(this,this.events);this.events.T(this.player,g.YJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.ZJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Ib);this.events.T(window,"focus",this.X$);this.load();var b=g.mf("STYLE");(g.We("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.rf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Vjb=function(a){return a.player.getVideoData().Ld?"current":a.Z?"new":"current"},a4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Wjb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Tjb(f,Vjb(a))));b4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Zx;d&&(c.postParams={ad_tracking:d});if(b=g.QRa(b))if(b=g.In(b),b=g.Zd(b))a.C=g.WB(b,c)},b4=function(a,b,c){c=void 0===c?!0:c;
a.player.hf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Xjb(a);c=[];d=new g.XJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.V({I:"div",S:"ytp-ce-shadow"}),g.pU(a.player,a.B.element,4),a.D=new g.CG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Yjb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.pU(a.player,f.element,4);var h=new g.XJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Zjb(a,f,e)}else g.BF(new g.VC("buildEndscreenElement null",
e))}a.player.tf(c);a.Ib()}},Xjb=function(a){var b=g.wF(),c=g.xF();
c&&b&&a.endscreen.visualElement&&g.EB(g.HF)(void 0,c,b,a.endscreen.visualElement)},Yjb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:c4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:d4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.$u(b.title||"")},xa:b.title},{I:"div",S:b.aE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:c4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:d4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.$u(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],X:{href:d4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.$u(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:c4(b)}]};c=new g.V(c);var d=g.Xe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Ju(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.fW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.$u(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],X:{href:d4(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:c4(b)},{I:"div",S:"ytp-ce-expanding-icon",X:$jb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.AC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.$u(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:d4(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:c4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.Ju(c.element,"ytp-ce-placeholder");return c},c4=function(a){if(a.SV)var b=a.SV.thumbnails;
return $jb(b?b[b.length-1].url:null)},$jb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Zjb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Ju(b.element,"ytp-ce-force-expand"),e4(a,c.id,!0)):(g.Lu(b.element,"ytp-ce-force-expand"),g.Lu(b.element,"ytp-ce-element-hover"),e4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){akb(a,b,c)});
b.Ta("mouseleave",function(){bkb(a,b,c)});
a.player.U().B||b.Ta("click",function(){g.Ju(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){ckb(a,c,m)});
b.Ta("keypress",function(m){ckb(a,c,m)});
b.Ta("focus",function(){akb(a,b,c)});
b.Ta("blur",function(){bkb(a,b,c)});
b.Ta("touchstart",function(){akb(a,b,c)});
var l=g.Ze("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Lu(b.element,"ytp-ce-element-hover");g.Lu(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Ze("ytp-sb-subscribe",b.element));d(g.Ze("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},ckb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Iu(d,"ytp-ce-element");){g.Iu(d,"subscribe-label")&&dkb(a,b);
if(g.Iu(d,"ytp-ce-channel-subscribe"))return;d=g.sf(d)}if(!d||g.Iu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])bkb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Nba)dkb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.In(d4(a,b.targetUrl)),g.cH(g.Zd(c),void 0,b.sessionData);else{var e=g.oS(a.player.U())||a.player.getVideoData().Ld,f=function(){var h=d4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.JB(h);e&&n&&(n.v||
n.list)?a.player.Co(n.v,l,n.list,!1,void 0,m||void 0):g.Bwa(h,l)};
dkb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},d4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.vS(a)+b}else return"";return b},akb=function(a,b,c){g.Iu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Ju(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Bu(function(){g.Ju(b.element,"ytp-ce-element-hover")},200)).start():g.Ju(b.element,"ytp-ce-element-hover"),f4(a,c.h7),e4(a,c.id,!0))},bkb=function(a,b,c){g.Lu(b.element,"ytp-ce-element-hover");
g.Lu(b.element,"ytp-ce-force-expand");e4(a,c.id,!1)},e4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Nu(a.j[e].element,"ytp-ce-element-shadow-show",c)},f4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||a4(a))c&&c();else{b=ekb(a,b);var e=0,f=!1,h=new g.Bu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.oE(b[a],d)}},dkb=function(a,b,c){f4(a,b.clickUrls,c);
(a=g.xF())&&b.t7&&g.OF(a,b.visualElement)},ekb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(fkb(b[d],c));return a},fkb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},gkb=function(a){return"string"===typeof a?a:""},g4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},hkb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},h4=function(a){return a.value?a.value:null},i4=function(a){if(!a)return null;
var b=g.In(gkb(a.value));b=g.Zd(b);if(!b)return null;var c=g4(a.target,ikb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new hkb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},jkb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},mkb=function(a){if(!a)return null;
var b=g4(a.type,kkb),c=g4(a.trigger,lkb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=i4(a?a:null);return b?new jkb(b,c,a):null},nkb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},okb=function(a,b){return g.zb(a.action,b)},pkb=function(a,b){this.context=a;
this.j=b},qkb=function(a){return a.customMessage?j4("div","iv-card-message",a.customMessage):""},k4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},rkb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(j4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},j4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.$u(c);return{I:a,X:b,xa:c}},skb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.KC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.KC+");");c.dir=g.$u(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,X:c,V:d}},l4=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Xi.click,5)}},tkb=function(a,b){this.merchant=a;
this.price=b},ukb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},vkb=function(a,b){return b?b:ukb(a)?"current":"new"},m4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Ya=new Map;this.Za=new Map;this.context.J.addEventListener(g.YJ("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.ZJ("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},n4=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.xL(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.rb=!1});
a.context.j.Ta(b,"touchmove",function(){a.rb=!0})},wkb=function(a){var b;
return(null==(b=g.U(a,g.pG))?0:b.url)?g.U(a,g.pG).url:(a=g.U(a,g.lT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},o4=function(a,b,c){return{pX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
K_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
QK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},xkb=function(a,b,c){m4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Db=this.Na=this.Nb=this.C=this.isInitialized=!1;this.cards=[];this.tb=this.Z=this.Ka=this.G=this.Va=this.j=null;this.ma=[];this.qa=this.N=this.Hf=this.Fa=null;this.K=0;this.Ea=new g.Bu(function(){},c.W.Gi?4E3:3E3);
g.L(this,this.Ea);this.ob=new g.Bu(function(){});
g.L(this,this.ob);this.Aa=new pkb(c,function(e,f,h,l,m,n){n4(d,e,f,h,l,m,n)});
this.Y=new g.V({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Ocultar cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.L(this,this.Y);this.D=this.Y.element;this.gb=new g.CG(this.Y,330);g.L(this,this.gb);this.Jb=g.Ze("iv-drawer-header-text",this.D);this.B=g.Ze("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Nb&&p4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Nb=d.C)&&q4(d)});
this.Sa=new g.IK(this);g.L(this,this.Sa);this.J.addEventListener("videodatachange",this.xt.bind(this))},ykb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){p4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){q4(a)});
var c=b.headerText;g.Af(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.vF(b.trackingParams);a.N=g.vF(b.closeTrackingParams);a.Hf=g.vF(b.iconTrackingParams)},zkb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.dG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Xi:{},Zo:null,Dj:e.trackingParams?g.vF(e.trackingParams):null,Hf:f&&f.trackingParams?g.vF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
KC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};r4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.dG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:s4(a,c,b,f),sponsored:!1,Xi:o4(f,e,f.command),Zo:f.trackingParams?g.vF(f.trackingParams):null,Dj:e.trackingParams?g.vF(e.trackingParams):null,Hf:l&&l.trackingParams?g.vF(l.trackingParams):null,imageUrl:t4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.dG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,KC:null,title:f.title?g.dG(f.title):"",customMessage:f.callToAction?g.dG(f.callToAction):"",url:g.U(f.command,g.pG).url?i4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.pG).url}):null,onClickCommand:null};r4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.dG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:s4(a,c,b,e),sponsored:!1,Xi:o4(e,f,e.endpoint),Zo:e.trackingParams?g.vF(e.trackingParams):null,Dj:f.trackingParams?g.vF(f.trackingParams):null,Hf:l&&l.trackingParams?g.vF(l.trackingParams):null,channelId:g.U(e.endpoint,g.KU).browseId,customMessage:e.customText?g.dG(e.customText):null,profileImageUrl:t4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.dG(e.channelName):"",metaInfo:[e.subscriberCountText?g.dG(e.subscriberCountText):""],url:i4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(e.endpoint,g.KU).canonicalBaseUrl?g.U(e.endpoint,g.KU).canonicalBaseUrl:"/channel/"+g.U(e.endpoint,g.KU).browseId}),onClickCommand:null};r4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.dG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:s4(a,c,b,e),sponsored:!1,Xi:o4(e,f,e.action),Zo:e.trackingParams?g.vF(e.trackingParams):null,Dj:f.trackingParams?g.vF(f.trackingParams):null,Hf:l&&l.trackingParams?g.vF(l.trackingParams):null,SF:t4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.dG(e.customMessage):null,playlistVideoCount:g.dG(e.playlistVideoCount),title:e.playlistTitle?g.dG(e.playlistTitle):"",metaInfo:[e.channelName?g.dG(e.channelName):
"",e.videoCountText?g.dG(e.videoCountText):""],url:i4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:wkb(e.action)}),onClickCommand:null};r4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.dG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:s4(a,c,b,e),sponsored:!1,Xi:o4(e,f,e.action),Zo:e.trackingParams?g.vF(e.trackingParams):null,Dj:f.trackingParams?g.vF(f.trackingParams):null,Hf:l&&l.trackingParams?g.vF(l.trackingParams):null,SF:t4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.dG(e.lengthString):null,customMessage:e.customMessage?g.dG(e.customMessage):null,title:e.videoTitle?g.dG(e.videoTitle):"",metaInfo:[e.channelName?g.dG(e.channelName):
"",e.viewCountText?g.dG(e.viewCountText):""],isLiveNow:!!e.badge,url:i4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:wkb(e.action)}),onClickCommand:null};r4(a,b)}}}}}a.K++},t4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},s4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Bkb=function(a,b){if(b=Akb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.fg.id),g.rf(b.WM),g.Fb(a.cards,b),a.SG(),u4(a)},p4=function(a,b,c){if(!a.C){a.gb.show();
a.Va=new g.Bu(function(){g.Ju(a.context.J.getRootNode(),g.TY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Sa.T(a.B,"mousewheel",function(h){a.Ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.xF();d&&a.Fa&&a.N&&g.MF(d,[a.Fa,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.dY||(f.dY=!0,Ckb(a.context.logger,f.fg.Xi.pX,b)),d&&g.MF(d,[f.fg.Zo]);S3(a.J);c&&(a.G=new g.Bu(function(){a.Ka=a.Z;a.tb.focus()},330),a.G.start())}},q4=function(a){a.C&&(a.gb.hide(),g.KC(a.Sa),g.Lu(a.context.J.getRootNode(),g.TY.IV_DRAWER_OPEN),a.C=!1,S3(a.J),a.G&&a.G.stop(),a.G=new g.Bu(function(){a.Ka&&(a.Ka.focus(),a.Ka=null)},330),a.G.start())},Ekb=function(a){g.Ku(a.Ab(),
[g.TY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.pU(a.J,a.D,5);Dkb(a);a.Z=g.Ze("ytp-cards-button",a.J.getRootNode());a.tb=g.Ze("iv-drawer-close-button",a.D);a.isInitialized=!0},Dkb=function(a){var b=g.Ze("iv-drawer-close-button",a.D);
a.context.j.Ta(b,"click",a.X4,a);a.context.j.Ta(a.B,"touchend",function(){a.Ea.start()});
a.context.j.Ta(a.B,"scroll",a.t5,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Iu(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.CE("iv-button-shown",a.L7,a));a.ma.push(g.CE("iv-button-hidden",a.K7,a));Fkb(a)},Fkb=function(a){a.ma.push(g.CE("iv-teaser-shown",a.H1,a));
a.ma.push(g.CE("iv-teaser-hidden",a.M7,a));a.ma.push(g.CE("iv-teaser-clicked",a.G1,a));a.Db=!0},Gkb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.U(b.onClickCommand,g.kgb))?void 0:c.targetId)?(a.qa=b,!0):!1},Hkb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.oQa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.U(h[0],g.LYa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},r4=function(a,b){if(!Gkb(a,b)||Hkb(a,b)){var c=Ikb(a,b);
if(c){var d={fg:b,WM:c.element,dY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Db||Fkb(a),Bkb(a,b.id),c=Jkb(a,d),g.Rb(a.cards,c,0,d));else{a.isInitialized||Ekb(a);Bkb(a,b.id);var e=Jkb(a,d);g.Rb(a.cards,e,0,d);c.Da(a.B,e);a.SG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,u4(a),Kkb(a,d),p4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Lkb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Lkb(a,
d)}),u4(a))}}},Ikb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=skb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?h4(b.url)||"":""},V:[k4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[j4("h2",void 0,b.title),d]}]}]};c=new g.V(c);l4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],X:{href:h4(b.url)||"","data-ytid":b.channelId},V:[k4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[qkb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},rkb(b)]}]}]};c=new g.V(c);l4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:h4(b.url)||""},V:[k4(b.SF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[qkb(b),j4("h2","iv-card-primary-link",b.title),rkb(b)]}]}]};
c=new g.V(c);l4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=skb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?h4(b.url)||"":"";c={I:"div",Ma:c,X:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Patrocinado",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[j4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.mf("span");g.Af(d,"Voc\u00ea v\u00ea este produto porque achamos que ele \u00e9 relevante para o v\u00eddeo. O Google pode ser compensado pelo comerciante.");
c.Yd(d,"adInfo");l4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],xa:"AO VIVO AGORA"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:h4(c))||""},V:[k4(b.SF,d),{I:"div",S:"iv-card-content",V:[qkb(b),j4("h2","iv-card-primary-link",b.title),rkb(b),f]}]}]};c=new g.V(e);l4(a,g.Ye("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Jkb=function(a,b){if(0===a.cards.length)return 0;
a=g.Bb(a.cards,function(c){return b.fg.startMs>c.fg.startMs||b.fg.startMs===c.fg.startMs&&b.fg.timestamp>=c.fg.timestamp?!0:!1});
return-1===a?0:a+1},Mkb=function(a){if(a.j)return"productListing"===a.j.fg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.mr(a.cards,function(c){return"productListing"===c.fg.type})}return g.mr(a.cards,function(c){return"productListing"===c.fg.type})},u4=function(a){g.Nu(a.J.getRootNode(),"ytp-cards-shopping-active",Mkb(a))},Lkb=function(a,b){if(!g.Iu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.xF(),d=a.j?a.j.fg.Hf:a.Hf;
c&&d&&g.NF(c,[d]);a.j=b;u4(a)}(c=a.isInitialized&&"none"==a.Ab().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.fg.teaserDurationMs&&a.J.pB(!0,{teaserText:b.fg.teaserText,durationMs:b.fg.teaserDurationMs,onClickCommand:b.fg.onClickCommand});a.ob.isActive()||((!a.C||!a.Ea.isActive()&&a.Na)&&Kkb(a,b),a.ob.start(910+b.fg.teaserDurationMs))}},Kkb=function(a,b){a.Y.Cb?(b=new X3([0,
a.B.scrollTop],[0,b.WM.offsetTop],600,Qjb),a.context.C.Ta(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ta(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.$F(a.Y,!0),a.B.scrollTop=b.WM.offsetTop,g.$F(a.Y,!1))},v4=function(a){return a.j&&a.j.fg?a.j.fg:a.cards[0]&&a.cards[0].fg?a.cards[0].fg:null},Akb=function(a,b){return g.zb(a.cards,function(c){return c.fg.id===b})},w4=function(a,b,c){m4.call(this,a,b);
this.annotation=c;this.isActive=!1},Nkb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},x4=function(a,b,c){w4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Okb=function(a,b){var c=void 0===c?0:c;
var d=Hjb(b).width;g.as(b,d);c=new Ojb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Pjb);g.L(a,c);a.context.C.Ta(c,"begin",function(){g.gs(b,!0)});
c.play()},Rkb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.fW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J),a.j.Da(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.gs(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.Vr(l,"right",b.image_width+"px");g.of(a.Ab(),l);a.C=new g.Bu(function(){Pkb(a,h,l)},500);
g.L(a,a.C);a.context.j.Ta(a.Ab(),"mouseover",function(){Qkb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Ab(),"mouseout",function(){a.C.start()})}},Qkb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.fs(b);a.j||(b.style.width=g.$r(f.width,!0),c.style.width=g.$r(f.width,!0));g.Vr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Vr(d,"right","1px");a.D=!0;g.gs(b,!0);a.G=new g.Bu(function(){g.Ju(this.Ab(),"iv-branding-active")},0,a);
a.G.start()}},Pkb=function(a,b,c){g.Lu(a.Ab(),"iv-branding-active");
a.K=new g.Bu(function(){g.gs(b,!1);a.j||(c.style.width=g.$r(0,!0))},250);
a.K.start();a.D=!1},Skb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Tkb=function(a,b,c){w4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.Bu(function(){d.j.setAttribute("aria-hidden","true");g.gs(d.C,!1);g.gs(d.B,!0)},700,this);
g.L(this,this.G)},Wkb=function(a,b,c){c.stopPropagation();
Ukb(a);Vkb(a,b);a.j.focus()},Xkb=function(a){a.isCollapsed||a.Z||a.D||(g.Ju(a.Ab(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Ukb=function(a){a.G.stop();
a.isCollapsed&&(g.Mu(a.Ab(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.gs(a.B,!1),g.gs(a.C,!0))},Vkb=function(a,b){a.D||(a.D=g.ng(function(){Ykb(this);
Xkb(this)},b,a))},Ykb=function(a){a.D&&(g.Ra.clearTimeout(a.D),a.D=null)},Zkb=function(a){this.J=a},Ckb=function(a,b,c){b&&(c?y4(a,b.map(function(d){return g.pu(d,c)})):y4(a,b))},y4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.oE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},$kb=function(a){g.wV.call(this,a);
var b=this;this.Y=this.N=!1;this.loadNumber=0;this.K={};this.logger=new Zkb(this.player);this.D=new g.IK(this);this.G=this.yx=null;this.events=new g.IK(this);this.Vg=this.Z=this.j=null;this.ma=[];g.L(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.I1,this);this.subscribe("resize",this.zJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.nZ,this);g.L(this,this.events);this.qa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.V({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.pU(this.player,this.B.element,4);this.B.hide();this.C=new g.V({I:"div",Ma:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.qa);this.C.element.appendChild(a);this.pu()&&this.load();var c=this.createElement({I:"style"});(g.We("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.rf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},alb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.gs(a,!1);return a},blb=function(a,b){b=!b.isCued()&&!g.JG(b,1024);
g.$F(a.B,b);g.$F(a.C,b)},clb=function(a,b,c){a.N=!0;
a.G=g.WB(b,c)},dlb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.$a(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(dlb(a,e))}return c},hlb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.QB(h)&&h.responseXML?h.responseXML:null)&&elb(a,h)}};
g.cD()&&(d.onFinish=flb(a,d.onFinish));d.postParams={ic_only:"1"};glb(d,c);a.N=!0;g.WB(b.Va,d)}}},glb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.XG&&(a.postParams.ic_coll=b.XG);b.XM&&(a.postParams.ic_xml=b.XM);b.WK&&(a.postParams.ic_track=b.WK)},ilb=function(a){var b=new g.V({I:"div"});
g.gs(b.element,!1);var c=new xkb(a.player,b.element,z4(a));g.L(c,b);b.Da(a.B.element);c.FF();return c},klb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.Y=!0,jlb(a,b),b.headerText&&a.Vg&&(c=g.dG(b.headerText),a.Vg.setAttribute("title",c))},z4=function(a){if(!a.Z){var b=new Rjb(a);
g.L(a,b);var c=new g.$o(a);g.L(a,c);a.Z=new Skb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.ij)}return a.Z},elb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.xF();if(e){var f=g.wF();f&&g.EB(g.ava)(void 0,e,f,[g.vF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=dlb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=g4(f.type,llb),p=g4(f.style,mlb),q=gkb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=mkb;if(null==t)var u=null;else if(g.Za(t)){l=[];for(var x=g.v(t),B=x.next();!B.done;B=x.next()){var F=f(B.value);
F&&l.push(F)}u=l}else{var G=f(t);u=G?[G]:[]}e=m&&n?new nkb(m,n,p,u,r):null}else e=null}catch(na){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=alb(f),O=null;switch(l.type){case "branding":if(f.player.U().ye)break;f.B.element.appendChild(H);O=new x4(H,z4(f),l);break;case "promotion":g.pU(f.player,H,4),O=new Tkb(H,z4(f),l)}O&&O.FF();if(f=O)g.L(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=ilb(a),g.L(a,a.j));if("card"===e.type){c=a.j;var P=e&&e.data&&e.data.card_type;
f=e.data;if(P)switch(l=f.tracking||{},l={pX:l.impression,click:l.click,close:l.close,K_:l.teaser_impression,QK:l.teaser_click},H=f.tracking_params||{},O=null,P){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Xi:l,Zo:H.card?g.vF(H.card):null,Dj:H.teaser?g.vF(H.teaser):null,Hf:H.icon?g.vF(H.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};r4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Xi:l,Zo:H.card?g.vF(H.card):null,
Dj:H.teaser?g.vF(H.teaser):null,Hf:H.icon?g.vF(H.icon):null,SF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};r4(c,e);break;case "productListing":f.signin_url&&(O=i4({target:"current",value:f.signin_url}));P=[];for(var Y=f.offers||[],la=0;la<Y.length;la++)P.push(new tkb(g.ze(Y[la].merchant),g.ze(Y[la].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Xi:l,Zo:H.card?g.vF(H.card):null,Dj:H.teaser?g.vF(H.teaser):null,Hf:H.icon?g.vF(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,KC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Hjb:O,Gjb:f.signin_title?f.signin_title:void 0,Fjb:f.signin_message?f.signin_message:void 0,offers:P,onClickCommand:null};r4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Xi:l,Zo:H.card?g.vF(H.card):
null,Dj:H.teaser?g.vF(H.teaser):null,Hf:H.icon?g.vF(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,KC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};r4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Xi:l,Zo:H.card?g.vF(H.card):null,Dj:H.teaser?g.vF(H.teaser):null,Hf:H.icon?g.vF(H.icon):null,SF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},r4(c,e)}}else ykb(a.j,e);c=!0}}c&&
(S3(a.player),a.zJ())},jlb=function(a,b){var c=!1;
a.j||(a.j=ilb(a),g.L(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(zkb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.GT(f)||(c=a.j,d=b.headerText?g.dG(b.headerText):"",g.Af(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.vF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.vF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Hf=b.icon.infoCardIconRenderer.trackingParams?g.vF(b.icon.infoCardIconRenderer.trackingParams):null,a.zJ());S3(a.player)}},nlb=function(a,b,c,d,e){if(!a.player.U().ye){var f=[];
b.navigationEndpoint&&g.U(b.navigationEndpoint,g.KU)&&g.U(b.navigationEndpoint,g.KU).browseId&&f.push(new jkb("openUrl","click",new hkb("/channel/"+g.U(b.navigationEndpoint,g.KU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.U(b.subscribeButton,
g.zT)){d.channel_id=g.U(b.subscribeButton,g.zT).channelId;var l;b=g.U(b.subscribeButton,g.zT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.dG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.dG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.dG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.dG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.U(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.J2))?void 0:m.url)||"";l={subscribeText:g.dG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.dG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new nkb(c,"branding","branding",f,d);l=alb(a);a.B.element.appendChild(l);f=new x4(l,z4(a),f);f.FF();g.L(f,f);a.K[c]=f}},flb=function(a,b){return function(){var c=g.Ka.apply(0,arguments);
a.isDisposed()||a.ma.push(g.tu.Hi(function(){b.apply(null,g.ra(c))}))}},olb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.hU.prototype.pB=g.ca(29,function(a,b){var c=g.NV(this.zb());c&&c.pB(a,b)});
var U3={},V3=null;g.lb(X3,g.Vu);g.k=X3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;W3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.rJ();this.Xl("play");this.isPaused()&&this.Xl("resume");this.j=1;var b=g.db(this);b in U3||(U3[b]=this);Kjb();Ljb(this,a);return!0};
g.k.stop=function(a){W3(this);this.j=0;a&&(this.progress=1);Mjb(this,this.progress);this.Xl("stop");this.wr()};
g.k.pause=function(){this.isPlaying()&&(W3(this),this.j=-1,this.Xl("pause"))};
g.k.ya=function(){0==this.j||this.stop(!1);this.Xl("destroy");X3.Nf.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.wL=function(){this.Xl("animate")};
g.k.Xl=function(a){this.dispatchEvent(new Njb(a,this))};
g.lb(Njb,g.wb);g.lb(Y3,X3);Y3.prototype.C=function(){};
Y3.prototype.wL=function(){this.C();Y3.Nf.wL.call(this)};
Y3.prototype.wr=function(){this.C();Y3.Nf.wr.call(this)};
Y3.prototype.rJ=function(){this.C();Y3.Nf.rJ.call(this)};
g.lb(Ojb,Y3);Ojb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Rjb,g.J);g.k=Rjb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.fb)(c,d||this.B);a=g.EC(a,b,c);this.j.push(a);return a};
g.k.QI=function(a,b,c,d){c=(0,g.fb)(c,d||this.B);a=Ijb(a,b,c);this.j.push(a);return a};
g.k.Mc=function(a){g.FC(a);g.Fb(this.j,a)};
g.k.Lf=function(){g.FC(this.j);this.j.length=0};
g.k.ya=function(){this.Lf();g.J.prototype.ya.call(this)};g.w(Ujb,g.wV);g.k=Ujb.prototype;g.k.load=function(){g.wV.prototype.load.call(this);if(!a4(this)){var a=g.RRa(this.player.getVideoData());a?(a=Tjb(a,Vjb(this)),b4(this,a,!1)):Wjb(this)}};
g.k.unload=function(){b4(this,null);this.C&&(this.C.abort(),this.C=null);g.wV.prototype.unload.call(this)};
g.k.Dh=function(a,b){return a4(this)?"loadCustomEndscreenRenderer"===a?(a=Tjb(b,"new"),b4(this,a),!0):null:null};
g.k.getOptions=function(){return a4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ib=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<plb.length;f++){var h=Math.abs(b.width-plb[f]);if(-1===e||d>=h)e=f,d=h}d=qlb[e];this.B&&g.Vr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.es(e.element,m,f);g.as(e.element,n,p);g.Mu(e.element,rlb);256<m||256<f?g.Ju(e.element,"ytp-ce-large-round"):96<m||96<f?g.Ju(e.element,"ytp-ce-medium-round"):g.Ju(e.element,"ytp-ce-small-round");g.Mu(e.element,slb);m=h.left+h.width/2;h=h.top+l/2;g.Ju(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Mu(e.element,qlb);g.Ju(e.element,d);(e=g.Xe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Vr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())f4(this,this.endscreen.impressionUrls),(a=g.xF())&&this.endscreen.visualElement&&g.LF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Ju(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Ju(b,"ytp-ce-shown");f4(this,c.impressionUrls);(b=g.xF())&&g.LF(b,c.visualElement);this.player.U().K&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Lu(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Lu(b,"ytp-ce-shown");this.player.U().K&&this.player.Qa("endscreenelementhidden",a)}};
g.k.X$=function(a){var b=this;a.target===window&&(new g.Bu(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Mu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var plb=[346,426,470,506,570,640,853,1280,1920],qlb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),slb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],rlb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var ikb={wsa:"current",vSa:"new"};var kkb={CLOSE:"close",WVa:"openUrl",SUBSCRIBE:"subscribe"},lkb={Mqa:"click",CLOSE:"close",PDa:"hidden",l0a:"rollOut",m0a:"rollOver",W1a:"shown"};nkb.prototype.bf=function(){var a=okb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var mlb={Dla:"anchored",W0:"branding",CHANNEL:"channel",ksa:"cta",SDa:"highlightText",THa:"label",PLAYLIST:"playlist",DYa:"popup",T4a:"speech",SUBSCRIBE:"subscribe",l8a:"title",VIDEO:"video",Deb:"website"},llb={W0:"branding",Boa:"card",Aua:"drawer",RDa:"highlight",WNa:"marker",g_a:"promotion",TEXT:"text",ggb:"widget"};g.w(m4,g.J);g.k=m4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.XJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.Za.set(a,e);this.context.J.tf([a])};
g.k.FF=function(){this.context.B.subscribe("resize",this.SG,this)};
g.k.Ab=function(){return this.element};
g.k.xL=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.rf(this.Ab())};
g.k.SG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=h4(a);if(f){var h=vkb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Ld||!1,n=g.JB(f||"");m&&n&&(n.v||n.list)?e.context.J.Co(n.v,b,n.list,!1):g.cH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);y4(this.context.logger,c,l,d);ukb(f)||(c=g.xF(),d=b.itct,c&&d&&g.OF(c,g.vF(d)))}};
g.k.ya=function(){this.Ya.clear();this.Za.clear();g.J.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.L(this,a);return a.element};g.w(xkb,m4);g.k=xkb.prototype;g.k.xt=function(){this.qa&&r4(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.fs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.SG=function(){var a=this.isAvailable();g.gs(this.Ab(),a);g.Nu(this.context.J.getRootNode(),g.TY.IV_DRAWER_ENABLED,a);S3(this.J)};
g.k.destroy=function(){this.J.pB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.DE(this.ma);g.KC(this.Sa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();m4.prototype.destroy.call(this)};
g.k.X4=function(){if(this.C){y4(this.context.logger,v4(this).Xi.close);var a=g.xF();a&&this.N&&g.OF(a,this.N);q4(this)}};
g.k.t5=function(){g.Nu(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.L7=function(){var a=g.xF(),b=v4(this);b=b?b.Hf:this.Hf;a&&b&&g.MF(a,[b])};
g.k.K7=function(){var a=g.xF(),b=v4(this);b=b?b.Hf:this.Hf;a&&b&&g.NF(a,[b])};
g.k.H1=function(){var a=v4(this);y4(this.context.logger,a.Xi.K_);var b=g.xF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Dj&&c.push(a.Dj);a.Hf&&c.push(a.Hf);0<c.length&&g.MF(b,c)}else g.MF(b,[a.Dj,a.Hf])};
g.k.M7=function(){var a=g.xF(),b=v4(this);a&&b&&g.NF(a,[b.Dj])};
g.k.G1=function(a){var b=v4(this),c=g.xF();this.j?a?(a=this.context.logger,y4(a,b.Xi.QK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Dj&&g.OF(c,b.Dj)):(a=this.context.logger,y4(a,b.Xi.QK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Hf&&g.OF(c,b.Hf)):(a=this.context.logger,y4(a,b.Xi.QK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Hf&&g.OF(c,this.Hf))};g.w(w4,m4);w4.prototype.FF=function(){m4.prototype.FF.call(this);Nkb(this)};
w4.prototype.show=function(){m4.prototype.show.call(this);var a=g.xF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.MF(a,[g.vF(b.itct)])};
w4.prototype.hide=function(){m4.prototype.hide.call(this);var a=g.xF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.NF(a,[g.vF(b.itct)])};g.w(x4,w4);
x4.prototype.Zw=function(){g.Ju(this.Ab(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],X:{"aria-label":"Marca-d'\u00e1gua do canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.gs(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ab().appendChild(b);var c=this.annotation.bf();c&&n4(this,b,c,this.annotation.id,a.session_data);Rkb(this,a)};
x4.prototype.show=function(){if(!this.isActive&&(w4.prototype.show.call(this),this.N||(this.Zw(),this.N=!0),g.gs(this.Ab(),!0),this.isActive=!0,this.B)){try{Okb(this,this.B)}catch(a){}g.Ju(this.context.J.getRootNode(),"ytp-branding-shown")}};
x4.prototype.hide=function(){this.isActive&&(w4.prototype.hide.call(this),g.gs(this.Ab(),!1),this.isActive=!1,g.Lu(this.context.J.getRootNode(),"ytp-branding-shown"))};
x4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);w4.prototype.destroy.call(this)};g.w(Tkb,w4);g.k=Tkb.prototype;
g.k.Zw=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ab().setAttribute("aria-hidden","true");this.Ab().setAttribute("aria-label","Promo\u00e7\u00e3o");this.Ab().tabIndex=0;var e=this.annotation.bf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&n4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Kn(f,h4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&n4(this,
this.Ab(),e,this.annotation.id,b.session_data,void 0,c)}g.Ju(this.j,"iv-click-target");e&&n4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],xa:"AO VIVO AGORA"})),g.Ju(this.j,"iv-click-target"),e&&n4(this,this.j,e,this.annotation.id,b.session_data,
void 0,c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expandir";this.context.j.Ta(this.B,"click",function(q){Wkb(a,5E3,q)});
c.appendChild(this.B);g.gs(this.B,!1);this.context.j.Ta(this.Ab(),"mouseover",this.I6,this);this.context.j.Ta(this.Ab(),"mouseout",this.H6,this);this.context.j.Ta(this.Ab(),"touchend",function(q){Wkb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Fechar";this.context.j.Ta(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.D6:this.C6,this);c.appendChild(this.C);g.Ku(this.Ab(),d);h&&(g.of(this.Ab(),h),n&&h.appendChild(n));g.of(this.Ab(),this.N);g.of(this.Ab(),c)};
g.k.show=function(){this.isActive||(w4.prototype.show.call(this),this.Y||(this.Zw(),this.Y=!0),g.gs(this.Ab(),!0),g.ng(function(){g.Lu(this.Ab(),"iv-promo-inactive")},100,this),this.Ab().removeAttribute("aria-hidden"),this.isActive=!0,Ykb(this),Ukb(this),Vkb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Ju(this.Ab(),"iv-promo-inactive"),this.isActive=!1,this.Ab().setAttribute("aria-hidden","true"))};
g.k.xL=function(a,b,c,d,e,f){return this.isCollapsed?!1:w4.prototype.xL.call(this,a,b,c,d,e,f)};
g.k.I6=function(a){this.Z=!0;Wkb(this,500,a)};
g.k.H6=function(){this.Z=!1;Xkb(this)};
g.k.C6=function(a){a.stopPropagation();this.hide()};
g.k.D6=function(a){a.stopPropagation();Ykb(this);this.isCollapsed=!0;g.Ju(this.Ab(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();w4.prototype.destroy.call(this)};g.w($kb,g.wV);g.k=$kb.prototype;g.k.Dh=function(a,b){if(!olb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.p2(b))&&elb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Bkb(this.j,b),S3(this.player)),!0}return null};
g.k.getOptions=function(){return olb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.pu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Ld&&a.ma||g.$T(this.player.app)?!1:1===c&&!b.NU||a.Na.get(b.videoId)||g.HT(b)||g.SRa(b)?!0:!1};
g.k.zJ=function(){if(this.C){var a=this.player.kb().getVideoContentRect(!0);g.es(this.C.element,a.width,a.height);g.as(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Ok();a=this.j;b=b.width;g.Nu(a.D,"iv-drawer-small",426>=b);g.Nu(a.D,"iv-drawer-big",1280<=b)}};
g.k.I1=function(a){blb(this,a.state);g.JG(a.state,2)&&(this.Gk()&&this.Yo()&&2!==this.player.getPresentingPlayerType()&&this.qB(!1),this.pB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.QB(h)&&h.responseXML?h.responseXML:null)&&(elb(b,h),g.Ju(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.wV.prototype.load.call(this);blb(this,this.player.Qb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.cD()&&(a=flb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&glb(e,f);f=f&&(f.XM||f.XG);if(!c.OB||f)c.Va?clb(this,c.Va,e):(this.yx=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.GT(h))&&!b.Y&&klb(b,h)},this.player.addEventListener("videodatachange",this.yx));
g.pU(this.player,this.C.element,4);this.zJ();(f=g.HT(c))&&jlb(this,f);(f=g.SRa(c))&&f.featuredChannel&&nlb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Vg=g.Ze("ytp-cards-button",this.player.getRootNode());g.GT(c)&&klb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&clb(this,b.Va,a)};
g.k.unload=function(){this.player.hf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,S3(this.player));this.N=!1;this.G&&(this.G.abort(),this.G=null);this.Y=!1;this.K={};this.B.hide();g.wV.prototype.unload.call(this);this.C.detach();this.yx&&(this.player.removeEventListener("videodatachange",this.yx),this.yx=null)};
g.k.nZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?hlb(this):this.load())};
g.k.Gk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.Y};
g.k.Yo=function(){return!!this.j&&this.j.C};
g.k.qB=function(a,b,c){b=void 0===b?!1:b;this.Gk();this.j&&(a?c?p4(this.j,c,b):p4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):q4(this.j))};
g.k.pB=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.nZ,this);g.Lu(this.player.getRootNode(),g.TY.IV_DRAWER_OPEN);for(var a=this.ma,b=g.tu,c=0,d=a.length;c<d;c++)b.Ij(a[c]);this.ma.length=0;g.wV.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.L(this,a);return a.element};g.vV("annotations_module",$kb);g.vV("creatorendscreen",Ujb);})(_yt_player);
